### ISSUE TITLE
hope to add multi-language support

### ISSUE THREAD

**Issue by Gaoyifei1011** [VOLKANOGEDAY/FluentAbout#1]
希望能够添加多语言支持
hope to add multi-language support

目前该应用只有英文版本，希望未来能够支持更多语言的版本。
Currently, the app is only available in English, and it is hoped that more language versions will be supported in the future.

**Comment by VOLKANOGEDAY** [comment]
I'll add a form in readme following days so anyone wants to contribute could be able to fill the form and submit so I could expand language support.
