### ISSUE TITLE
FluentAbout shows storage capacity of secondary hard drive instead of C drive

### ISSUE THREAD

**Issue by infinitepower18** [VOLKANOGEDAY/FluentAbout#2]
Windows is installed on my PC's SSD but FluentAbout is showing the capacity of my data hard drive.

<img width="1579" alt="image" src="https://user-images.githubusercontent.com/44692189/202265206-6aab9eb0-9a62-46bd-8906-cac96aee1bdd.png">

**Comment by VOLKANOGEDAY** [comment]
Looks like your data hard drive is disk 0 and thats why fluentabout shows its size. Going to fix this in next update which I will release soon. Thanks for the feedback.

**Comment by VOLKANOGEDAY** [comment]
Hmm tried some fixes but none of them worked. Issue still persists.
